### ISSUE TITLE
How many unique queues can be created

### ISSUE THREAD

**Issue by dialtonetech** [horse-framework/horse-mq#114]
Hi,

how many unique queues can be created with storage?

how do you pull only one or more items from a given queue?

example:
lets say you have two or more clients sending messages to server and these are been queued, how do you allow only client/consumer to pull messages that are directed only to them?

**Comment by mhelvacikoylu** [comment]
Hi,

There is no queue limit. It depends on your RAM. But even with 1 GB RAM, you can create thousands unique queues, maybe million. Empty queues don't take up much space. If they have messages, again, it depends message counts and your RAM (if persistent, also depends on your free disk space)

When your queues are in Pull state, you can send pull request to queue to receive messages. A quick example from our unit test projects:

            HorseClient consumer = new HorseClient();
            await consumer.ConnectAsync("host");

            PullRequest request = new PullRequest();
            request.Queue = "queue-name";
            request.Count = 1;
            request.ClearAfter = ClearDecision.None;
            request.GetQueueMessageCounts = false;
            request.Order = MessageOrder.FIFO;

            PullContainer container1 = await consumer.Queues.Pull(request);
            Assert.Equal(PullProcess.Completed, container1.Status);
            Assert.NotEmpty(container1.ReceivedMessages);

**Comment by dialtonetech** [comment]
Thank you
